### PR TITLE
update to postCSS 8

### PR DESCRIPTION
**Pull request by ryuran**
Hello @jonathantneal 
Thank for your help again for https://github.com/ryuran/postcss-variables-prefixer

I tried to apply your advice on this postCSS plugin.
Let me know if something can be improved.

I participate to HacktoberFest so I appreciate a `hacktoberfest-accepted` label on this PR if you agree.

### CODE REVIEW

**Comment by lowvisiondave** [comment]
Would love to see this merged in as the TailwindCSS uses PostCSS 8 by default now.

**Comment by gregorybolkenstijn** [comment]
Anybody able to merge this as it seems to pass all checks?

**Comment by jburgerio** [comment]
Merging this PR would also close issue #15.

**Comment by romainmenke** [comment]
@jonathantneal I think this code can also be simplified further.

https://github.com/csstools/postcss-focus-visible/pull/13/files#diff-723a658216781d0bb415440870893c61755aaeb0d1cb4b5e0424cec1ca7033adR3-R12

```diff
diff --git a/src/onRule.js b/src/onRule.js
index 76621f5..82346b6 100644
--- a/src/onRule.js
+++ b/src/onRule.js
@@ -4,13 +4,8 @@ import options from './options'
 const onRule = rule => {
        const selector = rule.selector.replace(selectorRegExp, ($0, $1) => `${options.replaceWith}${$1}`)
 
-       // check if it was processed yet
-       if (options.preserve && rule.prev()?.selector === selector) return
-
-       const clone = rule.clone({ selector })
-
-       if (options.preserve) rule.before(clone)
-       else rule.replaceWith(clone)
+       if (options.preserve) rule.cloneBefore({ selector })
+       else rule.assign({ selector })
 }
 
 export const selectorRegExp = /(?<!\\):focus-visible([^\w-]|$)/gi
```

**Comment by JoeWoodward** [comment]
@jonathantneal I'm in need of this change. I'm using webpack and yarn. I've tried using the master branch but of course it doesn't include the dist/ folder so webpack complains when it tries to find dist/index.cjs.js as specified in the package.json -> main entry. 

Do you know when you'll be releasing this? Is there some other way I can use this that you would recommend?

Also need to use focus-within which has the same issue

**Comment by romainmenke** [comment]
@JoeWoodward we are working on it :)
There a whole log of plugins that need to be updated and we are trying to get through all of them asap.
You might not receive much further feedback or timing here, but releases are coming!

**Comment by JoeWoodward** [comment]
I'm aware that there are a lot more plugins that need to be fixed before we can use postcss-preset-env again, but in the meantime would it not be possible to release this one individually?

**Pull request merged**
